### ISSUE TITLE
How to build the hunspell to generate the used native libraries?

### ISSUE THREAD

**Issue by cselti** [thomas-joiner/HunspellBridJ#10]
I have updated my hunspell linux-x64 library to v1.4.2, but the result .so file is much bigger (9x-10x times), than the previous one (it's also true, when I build the user v1.3.4.

How do you build the native hunspell for smaller library size? 
A description or a build script could be useful about this - because the [hunspell](https://github.com/hunspell/hunspell) has been actively developed nowadays :)

**Comment by thomas-joiner** [comment]
The only thing I do differently from the standard automake build process is to run `strip` on the `.so` file after it has built.

**Comment by cselti** [comment]
Thanks - sorry for the late reply!
