### ISSUE TITLE
Update libraries. 

### ISSUE THREAD

**Issue by tmccombs** [thomas-joiner/HunspellBridJ#5]
It looks like most of the library binaries haven't been updated in 3 years.

**Comment by thomas-joiner** [comment]
I have updated the binaries for Windows (x86 and x86_64) and Linux (x86 and x86_64) to version 1.3.4 (the most recent). I do not have a Mac OS X machine available to build on.

**Comment by tmccombs** [comment]
Thanks

**Comment by thomas-joiner** [comment]
Found someone with a Mac that was able to compile for Mac as well.
